### ISSUE TITLE
Documentation sur le code de Morse

### ISSUE THREAD

**Issue by dragos-constantin-stoica** [AndreeaChiurciu/morse#1]
Chercher sur Google la description de code de Morse.

**Comment by MMihut** [comment]
Mihalcea Mihut

**Comment by MMihut** [comment]
http://fr.wikipedia.org/wiki/Morse_%28alphabet%29

Entree: A-Z, 0-9

**Comment by dragos-constantin-stoica** [comment]
Entree: A-Z, 0-9
