### ISSUE TITLE
CODE - application ligne de commande en python

### ISSUE THREAD

**Issue by dragos-constantin-stoica** [AndreeaChiurciu/morse#14]
Ecrire ou recuperer le code pour une application de type ligne de commande pour le codage/encodage de Morse.

**Comment by MMihut** [comment]
http://thelivingpearl.com/2013/01/08/morse-code-and-dictionaries-in-python-with-sound/

**Comment by dragos-constantin-stoica** [comment]
Voir 8730a74b309e000397796f9a7902d5e840867191
