### ISSUE TITLE
Documentation sur code en python pour Morse

### ISSUE THREAD

**Issue by dragos-constantin-stoica** [AndreeaChiurciu/morse#2]
Chercher sur Google si il y en a un example de code en python sur le code de Morse.

**Comment by Ddelia** [comment]
Delia Gateje

**Comment by Ddelia** [comment]
http://svn.python.org/projects/python/trunk/Demo/scripts/morse.py

**Comment by Ddelia** [comment]
http://thelivingpearl.com/2013/01/08/morse-code-and-dictionaries-in-python-with-sound/

**Comment by dragos-constantin-stoica** [comment]
<pre>
<code class="python">
import sys
CODE = {'A': '.-',     'B': '-...',   'C': '-.-.', 
        'D': '-..',    'E': '.',      'F': '..-.',
        'G': '--.',    'H': '....',   'I': '..',
        'J': '.---',   'K': '-.-',    'L': '.-..',
        'M': '--',     'N': '-.',     'O': '---',
        'P': '.--.',   'Q': '--.-',   'R': '.-.',
        'S': '...',    'T': '-',      'U': '..-',
        'V': '...-',   'W': '.--',    'X': '-..-',
        'Y': '-.--',   'Z': '--..',
        
        '0': '-----',  '1': '.----',  '2': '..---',
        '3': '...--',  '4': '....-',  '5': '.....',
        '6': '-....',  '7': '--...',  '8': '---..',
        '9': '----.' 
        }
def verify(string):
    keys = CODE.keys()
    for char in string:
        if char.upper() not in keys and char != ' ':
            sys.exit('Error the charcter ' + char + ' cannot be translated to Morse Code')
def main():
    
    msg = raw_input('MESSAGE: ')
    
    verify(msg)
    
    for char in msg:
        if char == ' ':
            print ' '*7,
        else:
            print CODE[char.upper()],
        
if __name__ == &quot;__main__&quot;:
    main()
</code>
</pre>

**Comment by dragos-constantin-stoica** [comment]
https://gist.github.com/ebuckley/1842461

https://www.daniweb.com/software-development/python/threads/389596/python-encodedecode-morse-code
