### ISSUE TITLE
Documentation sur application web en python

### ISSUE THREAD

**Issue by dragos-constantin-stoica** [AndreeaChiurciu/morse#7]
Chercher sur Google un example d'applicaton web en python.

**Comment by madalina1794** [comment]
Madalina Tanea 
Sorina Goran

**Comment by madalina1794** [comment]
https://docs.python.org/2/howto/webservers.html - comment on fait en general pour ecrire une application web en python, ce qu'on utilise
http://learnpythonthehardway.org/book/ex50.html - un petit exemple
http://webpy.org/docs/0.3/tutorial - des explications pour comprendre l'exemple
http://code.tutsplus.com/articles/python-from-scratch-create-a-dynamic-website--net-22787 un autre exemple avec des explications

**Comment by dragos-constantin-stoica** [comment]
<pre>
import web
urls = (
    '/', 'index'
)
class index:
    def GET(self):
        return "Hello, world!"
if __name__ == "__main__":
    app = web.application(urls, globals())
    app.run()
</pre>
